### PR TITLE
Sristy Paul-Task 1

### PR DESCRIPTION
**Pull request by sristy17**

### CODE REVIEW

**Comment by aku1310** [comment]
Hey @sristy17 , just wanted to know why you closed this PR as it looks the same as your open PR (will merge that soon though)

**Comment by sristy17** [comment]
> Hey @sristy17 , just wanted to know why you closed this PR as it looks the same as your open PR (will merge that soon though)

Actually I edited the Readme MD instead creating a new one..so.

**Comment by aku1310** [comment]
> Actually I edited the Readme MD instead creating a new one..so.

Ah no worries, saw it now. Just an FYI for future, you can just push the new changes to the same branch and it will update the PR as well :) Won't have to create a new PR too

**Comment by sristy17** [comment]
> > Actually I edited the Readme MD instead creating a new one..so.
> 
> Ah no worries, saw it now. Just an FYI for future, you can just push the new changes to the same branch and it will update the PR as well :) Won't have to create a new PR too

Ok got it thanks.

**Pull request closed without merging**
